version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  db:
    image: mysql:5.7
    container_name: mysql01
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'JournalWatch'
       MYSQL_USER: 'lesnik'
       MYSQL_PASSWORD: ',tkrf'
       MYSQL_ROOT_PASSWORD: ',tkrf'
  redis:
    image: "redis:alpine"
  web:
    build: .
    container_name: django01
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn -w 4 -b 0.0.0.0:8080 application.wsgi:application --timeout 300"
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8080"
    depends_on:
      - db
  celery:
    build: .
    command: celery -A application worker -l info
    volumes:
      - ./src:/src
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A application beat -l info
    volumes:
      - ./src:/src
    depends_on:
      - db
      - redis
