# Generated by Django 2.2.2 on 2019-06-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('DOI', models.CharField(max_length=255)),
                ('theme', models.CharField(choices=[('FD', 'Fluid Dynamics')], default='FD', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('article_file', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('article_url', models.URLField(max_length=1023)),
            ],
            options={
                'verbose_name': 'датированный',
                'verbose_name_plural': 'датированные',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('image_file', models.FileField(null=True, upload_to='images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='article.Article')),
            ],
            options={
                'verbose_name': 'датированный',
                'verbose_name_plural': 'датированные',
                'abstract': False,
            },
        ),
    ]
