# Generated by Django 2.2.2 on 2019-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'ключевое слово', 'verbose_name_plural': 'ключевые слова'},
        ),
    ]
