# Generated by Django 2.2.2 on 2019-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190709_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
