# Generated by Django 2.2.2 on 2019-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
