# Generated by Django 2.2.2 on 2019-07-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
