# Generated by Django 2.2.2 on 2019-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='DOI',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(choices=[('RL', 'Rheology'), ('WACE', 'Wettability and Capillary Effects'), ('NM', 'Numerical methods'), ('FIPM', 'Flows in Porous Media'), ('IAST', 'Interface and surface thermodynamics'), ('PAC', 'Polymers and colloids'), ('FMAV', 'Flow measurement and visualization'), ('MF', 'Multiphase flows'), ('FST', 'Flow stability and transition'), ('PLF', 'Particle-laden flows'), ('UC', 'Unclassified')], default='UC', max_length=191),
        ),
    ]
