# Generated by Django 2.2.2 on 2019-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190818_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
    ]
